name: Deployment Exercise 2
on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Install ESLint v8
        run: npm install --save-dev eslint@8
      - name: Run lint
        run: |
          npx eslint --ext .jsx --fix src
          npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: build code
        run: npm run build
      - name: Deploy code
        run: echo "Deploying code ....Derrick is the best DevOps engineer in the world"
      - name: Run lint
        run: |
          sudo apt-get update
          npx eslint --ext .jsx --fix src
          npm run lint
