name: Handle issues
on:
  issues:
  workflow_dispatch:

jobs:
  output_info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJson(github.event) }}"